# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'kubernetes-challenge'
  DOCKER_BUILDKIT: 1

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: Build
      displayName: Build Image
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
         command: build 
         repository: arjunt11/neu-app-kubernetes

    -  job: Push
       displayName: Push Image
       steps:
         - task: Docker@2
           displayName: Push
           inputs:
            command: push
            containerRegistry:
            repository: arjunt11/neu-app-kubernetes 

